= Requisiti
:allow-uri-read: 


Scopri come implementare Jenkins da https://bitnami.com/stack/jenkins/helm["Grafico di BitNami Helm"^]. Dopo aver implementato Jenkins nel cluster, è possibile registrare l'applicazione con Astra Control.

Jenkins è un'applicazione validata per Astra Control.

* https://docs.netapp.com/us-en/astra-control-center-2204/concepts/validated-vs-standard.html#validated-apps["Scopri la differenza tra un'applicazione validata e un'applicazione standard in Astra Control"^].


Queste istruzioni sono valide sia per Astra Control Service che per Astra Control Center.


NOTE: Le applicazioni implementate da Google Marketplace non sono state validate. Alcuni utenti segnalano problemi di rilevamento e/o backup con le implementazioni Google Marketplace di Postgres, MariaDB e MySQL.



== Requisiti

* Cluster aggiunto ad Astra Control.
+

NOTE: Per Astra Control Center, è possibile aggiungere prima il cluster ad Astra Control Center o aggiungere prima l'applicazione.

* Versioni aggiornate di Helm (versione 3.2+) e Kubectl installate su una macchina locale con il kubeconfig appropriato per il cluster


Astra Control non supporta attualmente https://plugins.jenkins.io/kubernetes/["Kubernetes plugin per Jenkins"^]. È possibile eseguire Jenkins in un cluster Kubernetes senza il plug-in. Il plug-in offre scalabilità al cluster Jenkins.



== Installare Jenkins

Due note importanti su questo processo:

* È necessario implementare l'applicazione dopo che il cluster è stato aggiunto ad Astra Control Service, non prima. Astra Control Center accetta le applicazioni prima o dopo l'aggiunta del cluster ad Astra Control Center.
* È necessario implementare il grafico Helm in uno spazio dei nomi diverso da quello predefinito.


.Fasi
. Aggiungere il repo grafico BitNami:
+
[listing]
----
helm repo add bitnami https://charts.bitnami.com/bitnami
----
. Creare il `jenkins` Namespace e implementazione di Jenkins all'interno dell'IT con il comando:
+
[listing]
----
helm install <name> bitnami/jenkins –-namespace <namespace> --create-namespace
–-set global.storageClass=<storage_class_name>
----
+

NOTE: Se le dimensioni del volume vengono modificate, utilizzare le unità Kibibyte (Ki), Mebibyte (mi) o Gibibibyte (Gi).

+
È necessario definire la classe di storage solo nelle seguenti situazioni:

+
** Si sta utilizzando Astra Control Service e non si desidera utilizzare la classe di storage predefinita.
** Stai utilizzando Astra Control Center e non hai ancora importato il cluster in Astra Control Center. In alternativa, è stato importato il cluster, ma non si desidera utilizzare la classe di storage predefinita.




.Risultato
Ciò consente di:

* Crea uno spazio dei nomi.
* Imposta la classe di storage corretta.


Una volta che i pod sono online, puoi gestire l'applicazione con Astra Control. Astra Control consente di gestire un'applicazione a livello di spazio dei nomi o utilizzando un'etichetta Helm.
